Vagrant.configure("2") do |config|
  config.vm.define "windows" do |windows|
      windows.vm.box = "tntechdcigadldap-f24/winadldap"
      windows.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 2
        vb.gui = true
      end
  end
end